// Windows Daemon Installer — Task Scheduler
// Creates a scheduled task that runs on logon with restart on failure
// Also generates a PowerShell wrapper for environment variable control

import { writeFileSync, mkdirSync, existsSync, unlinkSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';
import type { InstallOptions, DaemonStatus } from './install.js';

const TASK_NAME = 'POS-Dispatcher';
const WRAPPER_NAME = 'pos-dispatcher.ps1';

function getScriptsDir(): string {
  return join(homedir(), '.pos', 'scripts');
}

function getWrapperPath(): string {
  return join(getScriptsDir(), WRAPPER_NAME);
}

// ── PowerShell Wrapper ───────────────────────────────────────────────

function generatePsWrapper(entryPath: string, logPath: string, options: InstallOptions): string {
  const nodePath = process.execPath;
  const controlPlaneUrl = options.controlPlaneUrl ?? process.env['CONTROL_PLANE_URL'] ?? '';

  const envLines: string[] = [
    '$env:NODE_ENV = "production"',
    '$env:POS_DAEMON_FOREGROUND = "0"',
  ];

  if (controlPlaneUrl) envLines.push(`$env:CONTROL_PLANE_URL = "${escapePsString(controlPlaneUrl)}"`);
  if (options.deviceId) envLines.push(`$env:DEVICE_ID = "${escapePsString(options.deviceId)}"`);
  if (options.deviceToken) envLines.push(`$env:DEVICE_TOKEN = "${escapePsString(options.deviceToken)}"`);

  return `# Process OS Dispatcher — PowerShell wrapper
# Generated by pos-dispatcher install
# Do not edit manually — re-run install to regenerate

${envLines.join('\n')}

# Redirect output to log file
$logPath = "${escapePsString(logPath)}"
$logDir = Split-Path $logPath -Parent
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}

# Start node with the dispatcher entry point
& "${escapePsString(nodePath)}" "${escapePsString(entryPath)}" *>> $logPath
`;
}

function escapePsString(str: string): string {
  return str.replace(/"/g, '`"').replace(/\$/g, '`$');
}

// ── Install ──────────────────────────────────────────────────────────

export function installWindowsTask(
  entryPath: string,
  logPath: string,
  options: InstallOptions,
): void {
  const scriptsDir = getScriptsDir();
  mkdirSync(scriptsDir, { recursive: true });

  // Write the PowerShell wrapper
  const wrapper = generatePsWrapper(entryPath, logPath, options);
  const wrapperPath = getWrapperPath();
  writeFileSync(wrapperPath, wrapper, 'utf-8');
  console.log(`[Install] Wrote ${wrapperPath}`);

  // Remove existing task if present
  try {
    execFileSync('schtasks.exe', ['/Delete', '/TN', TASK_NAME, '/F'], { stdio: 'pipe' });
  } catch {
    // Task may not exist
  }

  // Create the scheduled task
  // /SC ONLOGON — run when any user logs on
  // /RL HIGHEST — run with highest privileges available to user
  // /F — force creation (overwrite if exists)
  try {
    execFileSync('schtasks.exe', [
      '/Create',
      '/SC', 'ONLOGON',
      '/TN', TASK_NAME,
      '/TR', `powershell.exe -NoProfile -ExecutionPolicy Bypass -File "${wrapperPath}"`,
      '/RL', 'HIGHEST',
      '/F',
    ], { stdio: 'pipe' });
    console.log(`[Install] Created scheduled task "${TASK_NAME}"`);
  } catch (err) {
    console.error('[Install] Failed to create scheduled task:', (err as Error).message);
    throw err;
  }

  // Start the task immediately
  try {
    execFileSync('schtasks.exe', ['/Run', '/TN', TASK_NAME], { stdio: 'pipe' });
    console.log(`[Install] Started task "${TASK_NAME}"`);
  } catch {
    console.warn('[Install] Could not start task immediately — it will start on next logon');
  }
}

// ── Uninstall ────────────────────────────────────────────────────────

export function uninstallWindowsTask(): void {
  // Stop the task
  try {
    execFileSync('schtasks.exe', ['/End', '/TN', TASK_NAME], { stdio: 'pipe' });
  } catch {
    // May not be running
  }

  // Delete the task
  try {
    execFileSync('schtasks.exe', ['/Delete', '/TN', TASK_NAME, '/F'], { stdio: 'pipe' });
    console.log(`[Uninstall] Deleted scheduled task "${TASK_NAME}"`);
  } catch {
    console.warn('[Uninstall] Task may not exist');
  }

  // Remove the wrapper
  const wrapperPath = getWrapperPath();
  if (existsSync(wrapperPath)) {
    unlinkSync(wrapperPath);
    console.log(`[Uninstall] Removed ${wrapperPath}`);
  }

  console.log('[Uninstall] Windows Task Scheduler task removed');
}

// ── Status ───────────────────────────────────────────────────────────

export function windowsTaskStatus(): DaemonStatus {
  try {
    const output = execFileSync('schtasks.exe', ['/Query', '/TN', TASK_NAME, '/FO', 'CSV', '/V'], {
      stdio: 'pipe',
    }).toString();

    const installed = output.includes(TASK_NAME);
    const running = output.includes('Running');

    return { installed, running, platform: 'windows', serviceName: TASK_NAME };
  } catch {
    return { installed: false, running: false, platform: 'windows' };
  }
}

// ── Start / Stop ─────────────────────────────────────────────────────

export function startWindowsTask(): void {
  execFileSync('schtasks.exe', ['/Run', '/TN', TASK_NAME], { stdio: 'pipe' });
  console.log(`[Service] Started "${TASK_NAME}"`);
}

export function stopWindowsTask(): void {
  execFileSync('schtasks.exe', ['/End', '/TN', TASK_NAME], { stdio: 'pipe' });
  console.log(`[Service] Stopped "${TASK_NAME}"`);
}
