// WSL2 Daemon Installer — the tricky one
//
// Two strategies:
// 1. Primary: Windows-side Task Scheduler task that runs
//    wsl.exe -d <distro> -- node <entry>
//    This keeps WSL alive as long as the task runs.
//
// 2. Fallback: If WSL systemd is available, install a systemd user service
//    inside WSL AND a Windows Task Scheduler "keep-alive" task that runs
//    wsl.exe --exec sleep infinity to prevent WSL from shutting down.

import { writeFileSync, mkdirSync, existsSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { getWslDistroName, hasSystemd } from './detect.js';
import { installSystemdService, uninstallSystemdService, systemdStatus, startSystemd, stopSystemd } from './linux.js';
import type { InstallOptions, DaemonStatus } from './install.js';

const WSL_TASK_NAME = 'POS-Dispatcher-WSL';
const WSL_KEEPALIVE_TASK = 'POS-WSL-KeepAlive';
const WSL_WRAPPER_NAME = 'pos-dispatcher-wsl.ps1';

function getScriptsDir(): string {
  return join(homedir(), '.pos', 'scripts');
}

function getWrapperPath(): string {
  return join(getScriptsDir(), WSL_WRAPPER_NAME);
}

/**
 * Convert a WSL Linux path to a Windows path for use in PowerShell/schtasks.
 * Example: /home/user/.pos/scripts -> \\wsl$\Ubuntu\home\user\.pos\scripts
 */
function toWindowsPath(linuxPath: string): string {
  try {
    const result = execFileSync('wslpath', ['-w', linuxPath], { stdio: 'pipe' }).toString().trim();
    return result;
  } catch {
    // Fallback: construct manually
    const distro = getWslDistroName() ?? 'Ubuntu';
    return `\\\\wsl$\\${distro}${linuxPath}`;
  }
}

/**
 * Find the Windows-side wsl.exe path from within WSL.
 */
function findWslExe(): string {
  try {
    const result = execFileSync('which', ['wsl.exe'], { stdio: 'pipe' }).toString().trim();
    if (result) return result;
  } catch {
    // Fallback to known path
  }
  return '/mnt/c/Windows/System32/wsl.exe';
}

// ── PowerShell Wrapper for Windows-Side Task ─────────────────────────

function generateWslWrapper(entryPath: string, logPath: string, options: InstallOptions): string {
  const distro = getWslDistroName() ?? 'Ubuntu';
  const controlPlaneUrl = options.controlPlaneUrl ?? '';

  const envExports: string[] = [
    'export NODE_ENV=production',
    'export POS_DAEMON_FOREGROUND=0',
  ];
  if (controlPlaneUrl) envExports.push(`export CONTROL_PLANE_URL='${controlPlaneUrl}'`);
  if (options.deviceId) envExports.push(`export DEVICE_ID='${options.deviceId}'`);
  if (options.deviceToken) envExports.push(`export DEVICE_TOKEN='${options.deviceToken}'`);

  const envBlock = envExports.join('; ');

  return `# Process OS Dispatcher — WSL launcher (PowerShell)
# Generated by pos-dispatcher install
# Launches the dispatcher inside WSL via wsl.exe

$distro = "${distro}"
$command = "${envBlock}; exec ${process.execPath} ${entryPath}"

# Start WSL with the dispatcher
wsl.exe -d $distro -- bash -c $command
`;
}

// ── Strategy 1: Windows-Side Task Scheduler ──────────────────────────

function installWindowsSideTask(entryPath: string, logPath: string, options: InstallOptions): void {
  const scriptsDir = getScriptsDir();
  mkdirSync(scriptsDir, { recursive: true });

  // Write the PowerShell wrapper
  const wrapper = generateWslWrapper(entryPath, logPath, options);
  const wrapperPath = getWrapperPath();
  writeFileSync(wrapperPath, wrapper, 'utf-8');
  console.log(`[Install:WSL] Wrote ${wrapperPath}`);

  // Convert to Windows path for schtasks
  const winWrapperPath = toWindowsPath(wrapperPath);

  // Remove existing task
  try {
    // Use wsl.exe to run schtasks on Windows side
    const wslExe = findWslExe();
    execFileSync(wslExe, [
      '-e', 'schtasks.exe', '/Delete', '/TN', WSL_TASK_NAME, '/F',
    ], { stdio: 'pipe' });
  } catch {
    // Task may not exist
  }

  // Create the task via schtasks.exe (accessible from WSL)
  try {
    const wslExe = findWslExe();
    execFileSync(wslExe, [
      '-e', 'schtasks.exe',
      '/Create',
      '/SC', 'ONLOGON',
      '/TN', WSL_TASK_NAME,
      '/TR', `powershell.exe -NoProfile -ExecutionPolicy Bypass -File "${winWrapperPath}"`,
      '/RL', 'HIGHEST',
      '/F',
    ], { stdio: 'pipe' });
    console.log(`[Install:WSL] Created Windows Task "${WSL_TASK_NAME}"`);
  } catch (err) {
    console.error('[Install:WSL] Failed to create Windows Task:', (err as Error).message);
    throw err;
  }

  // Start immediately
  try {
    const wslExe = findWslExe();
    execFileSync(wslExe, [
      '-e', 'schtasks.exe', '/Run', '/TN', WSL_TASK_NAME,
    ], { stdio: 'pipe' });
    console.log(`[Install:WSL] Started "${WSL_TASK_NAME}"`);
  } catch {
    console.warn('[Install:WSL] Could not start immediately — will start on next Windows logon');
  }
}

// ── Strategy 2: systemd + Windows keep-alive ─────────────────────────

function installSystemdWithKeepalive(entryPath: string, logPath: string, options: InstallOptions): void {
  // Install systemd service inside WSL
  console.log('[Install:WSL] systemd detected — installing systemd user service');
  installSystemdService(entryPath, logPath, options);

  // Also install a Windows-side keep-alive task to prevent WSL shutdown
  console.log('[Install:WSL] Installing Windows keep-alive task to prevent WSL shutdown');

  const distro = getWslDistroName() ?? 'Ubuntu';
  try {
    const wslExe = findWslExe();

    // Remove existing keep-alive task
    try {
      execFileSync(wslExe, [
        '-e', 'schtasks.exe', '/Delete', '/TN', WSL_KEEPALIVE_TASK, '/F',
      ], { stdio: 'pipe' });
    } catch {
      // May not exist
    }

    // Create keep-alive: wsl.exe --exec sleep infinity
    execFileSync(wslExe, [
      '-e', 'schtasks.exe',
      '/Create',
      '/SC', 'ONLOGON',
      '/TN', WSL_KEEPALIVE_TASK,
      '/TR', `wsl.exe -d ${distro} --exec sleep infinity`,
      '/RL', 'HIGHEST',
      '/F',
    ], { stdio: 'pipe' });
    console.log(`[Install:WSL] Created keep-alive task "${WSL_KEEPALIVE_TASK}"`);

    // Start the keep-alive
    execFileSync(wslExe, [
      '-e', 'schtasks.exe', '/Run', '/TN', WSL_KEEPALIVE_TASK,
    ], { stdio: 'pipe' });
  } catch (err) {
    console.warn('[Install:WSL] Could not create keep-alive task:', (err as Error).message);
    console.warn('[Install:WSL] WSL may shut down after idle timeout — systemd service will restart on next WSL start');
  }
}

// ── Public Install ───────────────────────────────────────────────────

export function installWslDaemon(
  entryPath: string,
  logPath: string,
  options: InstallOptions,
): void {
  console.log('[Install:WSL] Detected WSL2 environment');

  const distro = getWslDistroName();
  if (distro) {
    console.log(`[Install:WSL] Distribution: ${distro}`);
  }

  if (hasSystemd()) {
    // Strategy 2: systemd inside WSL + Windows keep-alive
    installSystemdWithKeepalive(entryPath, logPath, options);
  } else {
    // Strategy 1: Windows-side Task Scheduler launches into WSL
    console.log('[Install:WSL] No systemd — using Windows Task Scheduler to launch into WSL');
    installWindowsSideTask(entryPath, logPath, options);
  }
}

// ── Uninstall ────────────────────────────────────────────────────────

export function uninstallWslDaemon(): void {
  // Remove systemd service if present
  if (hasSystemd()) {
    uninstallSystemdService();
  }

  // Remove Windows-side tasks
  const wslExe = findWslExe();

  for (const taskName of [WSL_TASK_NAME, WSL_KEEPALIVE_TASK]) {
    try {
      execFileSync(wslExe, ['-e', 'schtasks.exe', '/End', '/TN', taskName], { stdio: 'pipe' });
    } catch { /* may not be running */ }
    try {
      execFileSync(wslExe, ['-e', 'schtasks.exe', '/Delete', '/TN', taskName, '/F'], { stdio: 'pipe' });
      console.log(`[Uninstall:WSL] Deleted Windows task "${taskName}"`);
    } catch { /* may not exist */ }
  }

  // Remove wrapper script
  const wrapperPath = getWrapperPath();
  if (existsSync(wrapperPath)) {
    unlinkSync(wrapperPath);
  }

  console.log('[Uninstall:WSL] WSL daemon removed');
}

// ── Status ───────────────────────────────────────────────────────────

export function wslDaemonStatus(): DaemonStatus {
  // Check systemd first (if available)
  if (hasSystemd()) {
    const sysStatus = systemdStatus();
    if (sysStatus.installed) {
      return { ...sysStatus, platform: 'wsl' };
    }
  }

  // Check Windows task
  try {
    const wslExe = findWslExe();
    const output = execFileSync(wslExe, [
      '-e', 'schtasks.exe', '/Query', '/TN', WSL_TASK_NAME, '/FO', 'CSV', '/V',
    ], { stdio: 'pipe' }).toString();

    const installed = output.includes(WSL_TASK_NAME);
    const running = output.includes('Running');
    return { installed, running, platform: 'wsl', serviceName: WSL_TASK_NAME };
  } catch {
    return { installed: false, running: false, platform: 'wsl' };
  }
}

// ── Start / Stop ─────────────────────────────────────────────────────

export function startWslDaemon(): void {
  if (hasSystemd()) {
    startSystemd();
    return;
  }

  const wslExe = findWslExe();
  execFileSync(wslExe, ['-e', 'schtasks.exe', '/Run', '/TN', WSL_TASK_NAME], { stdio: 'pipe' });
  console.log(`[Service:WSL] Started "${WSL_TASK_NAME}"`);
}

export function stopWslDaemon(): void {
  if (hasSystemd()) {
    stopSystemd();
    return;
  }

  const wslExe = findWslExe();
  execFileSync(wslExe, ['-e', 'schtasks.exe', '/End', '/TN', WSL_TASK_NAME], { stdio: 'pipe' });
  console.log(`[Service:WSL] Stopped "${WSL_TASK_NAME}"`);
}
